### ISSUE TITLE
Errors reported from Card dialogs

### ISSUE THREAD

**Issue by farling42** [MiahNelah/better-entity-link#10]
Foundry 11.307
Module 1.2.3.1

The following error is generated when clicking the Reset button in a Card Stack. I've also seen it generated from other interactions in the various Card Stacks dialog windows.

![image](https://github.com/MiahNelah/better-entity-link/assets/17485384/eb45d248-ba12-4684-be78-f817eef6a8f8)

**Comment by MiahNelah** [comment]
Same issue #9, I close this one.
