### ISSUE TITLE
FEATURE: Add actions for links to a JournalEntryPage

### ISSUE THREAD

**Issue by farling42** [MiahNelah/better-entity-link#13]
Add support for JournalEntryPage as well as JournalEntry.

Show image/text would definitely be appropriate, as would probably be configure ownership (although changing ownership on a page will have no effect if the containing JournalEntry doesn't have at least the same ownership).

**Comment by MiahNelah** [comment]
Please look at the latest version (1.5) with support for JournalEntryPage. Ownership parity between Journal and Page isn't enforced tough.

**Comment by farling42** [comment]
Yes, that's working fine.
