### ISSUE TITLE
FEATURE: Change manifest link to point to latest instead of explicit version

### ISSUE THREAD

**Issue by farling42** [MiahNelah/better-entity-link#14]
Every time this module is updated, the user is prompted to change the location of the manifest. It would be far better if the "manifest" line in module.json referred to "latest/download" instead of an explicit version. (The "download" line should remain pointing to a specific version.

e.g., my PDF Pager module has the following lines in module.json:

```
    "url": "https://github.com/farling42/fvtt-pdf-pager",
    "manifest": "https://github.com/farling42/fvtt-pdf-pager/releases/latest/download/module.json",
    "download": "https://github.com/farling42/fvtt-pdf-pager/releases/download/0.48.2/module.zip",
```

**Comment by MiahNelah** [comment]
I changed publishing links and github action, everything should works with no manifest URL change anymore.
