### ISSUE TITLE
FEATURE: Jump to Pin for Journal PAGE

### ISSUE THREAD

**Issue by farling42** [MiahNelah/better-entity-link#16]
Jumping to a scene pin was recently added for Journal Entries. It would be nice to also work with pins to Journal Entry Pages.

Something similar to, but might want extra code to switch to the relevant scene (as done for the other JumpPin).

```js
    BetterEntityLink.registerJournalEntryPageAction({
        name: "SIDEBAR.JumpPin",
        icon: "fa-crosshairs",
        condition: entity => !!entity.sceneNote,
        callback: async entity => canvas.notes.panToNote(entity.sceneNote)
    });
```

**Comment by MiahNelah** [comment]
It was not that easy because JournalEntryPage does not provide same features then JournalEntry. Plus, I had to allow to jump to specific page, or to journal. I just released a new version (v1.6) with this new action and some fixes to previous one.
