### ISSUE TITLE
[Feature Request] Integration of the old sound link module

### ISSUE THREAD

**Issue by p4535992** [MiahNelah/better-entity-link#6]
I think this module is the right place to merge all these kind of features.
Can you merge the fetaure from the module [Sound Link](https://github.com/superseva/sound-link) in this module ?

**Comment by MiahNelah** [comment]
Thanks for your feedback! I had never thought of integrating this kind of feature to this module, imagining mostly adding contextual menus. But now that you mention this feature, it's true that it would be interesting to add this kind of button everywhere.

**Comment by MiahNelah** [comment]
I just checked Sound Link and I don't really understand : from what I can see, this feature is already the default behavior of Foundry. You just have to drag & drop sound from playlist to journal. Is there something more than just play sound ?
