### ISSUE TITLE
Not working for me in v11 and latest update

### ISSUE THREAD

**Issue by Hoosjan** [MiahNelah/better-entity-link#9]
Hi! 
I'm afraid the module stopped working in v11 for me, is there anything I can do to fix this? Or is this an update that needs to be fixed?

I love to use it, kudo's for making it :-)

**Comment by MiahNelah** [comment]
Hello @Hoosjan ! Sorry for the delay. This issue should be fixed in version 1.2.3.1 I just released. Please tell me if you stil encounter issues.

**Comment by Hoosjan** [comment]
No reason to apologise :-) It's all in your spare time so take it easy. I'll test it out and report back.

**Comment by uniwars** [comment]
I get this error often in the console, like here when rolling a grapple athletics check :

![image](https://github.com/MiahNelah/better-entity-link/assets/65986545/f45a31b5-8fa6-4b80-b9ca-4c99b71fd088)


Last version, foundry v11 last stable, pf2e system last version

**Comment by MiahNelah** [comment]
So it's not related to PF2e. This error message is harmless and is happening when a card is creating into chatlog while this module is enabled. Module tried to apply context menu to embedded link into chat card, which is not possible.

This issue has been fixed in v1.2.4 !
